### ISSUE TITLE
Recursive clone failing

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-monitor#285]
Recursive clone of https://github.com/Seagate/cortx is failing due to cortx-monitor Repository. Please find attached detailed logs.

Log snippet -
Resolving deltas: 100% (9556/9556), done.
Submodule path 'cortx-monitor': checked out 'aa04ad0e185d381d39fefd205b76c76125ebd6aa'
No submodule mapping found in .gitmodules for path 'cortx-utils'

Recursive clone of cortx-monitor is also failing.
[root@ssc-vm-1613 ~]# git clone https://github.com/Seagate/cortx-monitor --recursive
Cloning into 'cortx-monitor'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 14917 (delta 14), reused 9 (delta 1), pack-reused 14878
Receiving objects: 100% (14917/14917), 63.22 MiB | 41.05 MiB/s, done.
Resolving deltas: 100% (9556/9556), done.
No submodule mapping found in .gitmodules for path 'cortx-utils'

Seems cortx-utils Repo link is added without .gitmodules in https://github.com/Seagate/cortx-monitor/pull/277

**Comment by shailesh-vaidya** [comment]
Recursive clone of cortx-monitor is working now. 
```
[root@ssc-vm-1613 ~]# git clone https://github.com/Seagate/cortx-monitor --recursive
Cloning into 'cortx-monitor'...
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 14919 (delta 15), reused 10 (delta 2), pack-reused 14878
Receiving objects: 100% (14919/14919), 63.22 MiB | 41.42 MiB/s, done.
Resolving deltas: 100% (9557/9557), done.
[root@ssc-vm-1613 ~]#
```
However it’s still failing for cortx repo. As submodule issue causing dispatch event failure. This dispatch event links latest cortx-monitor to cortx repo. Please refer - https://github.com/Seagate/cortx/runs/1775993708?check_suite_focus=true 

Raised https://github.com/Seagate/cortx/pull/631 for this.

**Comment by saurabhkhanvilkar** [comment]
@shailesh-vaidya , i think this issue can be closed now?

**Comment by shailesh-vaidya** [comment]
> @shailesh-vaidya , i think this issue can be closed now?

@saurabhkhanvilkar  Yes.  We are good with solution now. @mariyappanp  Thanks for fixing it.
