### ISSUE TITLE
Cleanup the spec file

### ISSUE THREAD

**Issue by ypise** [Seagate/cortx-monitor#369]
https://github.com/Seagate/cortx-monitor/blob/27f77896abc41a7882013b9f6115e7721e1c4513/low-level/sspl-ll.spec#L130

During the `%preun` stage, the actions are performed without any checks.
Please correct the section to:
```
%preun
# Remove configuration in case of uninstall
if [[ $1 = 0 ]]; then
  [[ rm -f /var/%{product_family}/sspl/sspl-configured ]] && /var/%{product_family}/sspl/sspl-configured
  [[ systemctl status sspl-ll.service > /dev/null ]] && systemctl stop sspl-ll.service 2> /dev/null
fi
```

**Comment by mariyappanp** [comment]
https://github.com/Seagate/cortx-monitor/pull/371
This PR carries required changes on sspl-ll.spec.

**Comment by cdeshmukh** [comment]
thanks @ypise  for pointing out, we have addressed it in https://github.com/Seagate/cortx-monitor/pull/371/files?file-filters%5B%5D=.spec
