### ISSUE TITLE
Sanity Test Stuck at "Waiting for SSPL to complete initialization"

### ISSUE THREAD

**Issue by daniarherikurniawan** [Seagate/cortx-monitor#505]
I tried to rerun the test after rebuilding + reinstalling the RPM. This is the Readme that I am following (https://github.com/Seagate/cortx-monitor/blob/thavanathan-patch-1/cortx-monitorQuickstartGuide.md).

I am able to follow the readme just fine. Everything works as expected. However, when I edit the code a bit and redo all the build+install, the sanity test is stuck. I feel like I am missing something. Perhaps the Readme above haven't provided the method to enable rebuild + retest.

To reproduce:
1. Re-execute the build script `jenkins/build.sh` 
2. Then follow all the step until running the sanity test
3. Do some code editing here
4. Repeat step 1 and 2, but this time. I got stuck at the sanity test: 
```sh
/opt/seagate/cortx/sspl/bin/sspl_setup test --config yaml:///etc/sspl_global_config_copy.yaml --plan dev_sanity
```

The trace:
```sh
[root@cmu ~]# systemctl status kafka
● kafka.service - Apache Kafka server (broker)
   Loaded: loaded (/etc/systemd/system/kafka.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2021-08-16 18:55:08 UTC; 1min 18s ago
     Docs: http://kafka.apache.org/documentation.html
 Main PID: 1260 (java)
   CGroup: /system.slice/kafka.service
           └─1260 java -Xmx1G -Xms1G -server -XX:+UseG1GC -XX:MaxGCPauseMill...

Aug 16 18:55:13 cmu kafka-server-start.sh[1260]: [2021-08-16 18:55:13,923] I...
Aug 16 18:55:13 cmu kafka-server-start.sh[1260]: [2021-08-16 18:55:13,923] I...
Aug 16 18:55:13 cmu kafka-server-start.sh[1260]: [2021-08-16 18:55:13,923] I...
Aug 16 18:55:13 cmu kafka-server-start.sh[1260]: [2021-08-16 18:55:13,924] I...
Aug 16 18:55:13 cmu kafka-server-start.sh[1260]: [2021-08-16 18:55:13,924] I...
Aug 16 18:55:13 cmu kafka-server-start.sh[1260]: [2021-08-16 18:55:13,924] I...
Aug 16 18:55:13 cmu kafka-server-start.sh[1260]: [2021-08-16 18:55:13,924] I...
Aug 16 18:55:13 cmu kafka-server-start.sh[1260]: [2021-08-16 18:55:13,924] I...
Aug 16 18:55:13 cmu kafka-server-start.sh[1260]: [2021-08-16 18:55:13,924] I...
Aug 16 18:55:13 cmu kafka-server-start.sh[1260]: [2021-08-16 18:55:13,924] I...
Hint: Some lines were ellipsized, use -l to show in full.
[root@cmu ~]#  /opt/seagate/cortx/sspl/bin/sspl_setup test --config yaml:///etc/sspl_global_config_copy.yaml --plan dev_sanity
Aug 16 18:56:31 sspl-setup[2694]: INFO test - Init done (sspl_setup:296)
Aug 16 18:56:36 sspl-setup[2694]: INFO test - Validation done (sspl_setup:340)
Aug 16 18:56:36 sspl-setup[2694]: INFO Ensured Package Dependency: Flask(v1.1.1). (sspl_test.py:94)
Starting mock server on 127.0.0.1:28200
 * Serving Flask app "mock_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Stoping the SSPL service
Code Coverage enabled : False
Starting the SSPL service
Waiting for SSPL to complete initialization of all the plugins..
```

My kafka is active as shown above. I also restarted the machine, but it doesn't solve the problem. I also tried to delete all the existing RPM and reinstall the newly generated RPM, but the problem still persist. 
I run this on devvm OVA. Please let me know if I need to provide more info.

Thanks!
cc: @cdeshmukh @thavanathan

**Comment by thavanathan** [comment]
This issue is resolved after following new QSG as commented by Dan. closing this.

**Comment by cortx-admin** [comment]
> Thavanathan Thangaraj commented in Jira Server:

[https://github.com/Seagate/cortx-monitor/issues/505]
{quote} 
h3. *[daniarherikurniawan|https://github.com/daniarherikurniawan]* commented [6 days ago|https://github.com/Seagate/cortx-monitor/issues/505#issuecomment-906517444]
|This problem is solved with the latest QSG! Thanks!|
{quote}

**Comment by cortx-admin** [comment]
> Thavanathan Thangaraj commented in Jira Server:

https://github.com/Seagate/cortx-monitor/issues/505

**Comment by cortx-admin** [comment]
> Thavanathan Thangaraj commented in Jira Server:

https://github.com/Seagate/cortx-monitor/issues/505

**Comment by cortx-admin** [comment]
> Thavanathan Thangaraj commented in Jira Server:

Completed.
